import type { Investigation } from "./types";

/**
 * Seeded from Google Drive vault (full crawl 2026-09-10/11):
 *
 * investigations/
 *   INVESTIGATION_MASTER_DISTILL.md
 *
 * Investigations/
 *   Epstein specific/
 *     CORE + PART1–5, Epstein-Maxwell-timeline, NPA DocumentCloud,
 *     IA archive link, Black Book torrent stub, Barak connections,
 *     Janet Epstein crossover, geneanet family tree scrape,
 *     Middlebury/, Palm Beach Pete/, Recap latest/, 4 fuckers/,
 *     30 swarms/, Swarm copies/, API BUILD/
 *   Hypothesis/
 *     DISCOVERY_METHODS 1–3, INVESTIGATION_PROCEDURES, theories.txt,
 *     MY THEORIES / File_01_Full THEORIES, maindata, ECHO SWARM
 *   recap/  (swarm api MASTER, start1–10, degsil map, seed story)
 *   Epstein's shit/  (swarm scripts + env stubs — keys NOT ingested)
 * investigations-audio/  (NLLA Newsom mp3 — meta only)
 *
 * Ceiling: public-record OSINT framing only.
 * Master distill §7: Simel=Epstein identity CONTRADICTED.
 * No secret-store contents, no keys, no CSAM, no private doxx.
 */
export const SEED_INVESTIGATIONS: Investigation[] = [
  {
    id: "east66-vault",
    code: "E66-01",
    title: "East 66 Vault",
    subtitle: "301 E 66 / Indyke / ACRIS / BC-PIPE",
    status: "active",
    color: "#e4dfd4",
    summary:
      "Standing public-record vault from MASTER DISTILL §2 + MAIN_INVESTIGATION_1953_TRUST_ENGORON_ROD: 301 East 66th Street network, Darren Indyke (PL-INDYKE), ACRIS deed roster, DocumentCloud + Internet Archive EpsteinDocs. Reports RPT-004 DocumentCloud/IA · RPT-005 Indyke H9 · RPT-006 East66 multi-party H5 · RPT-007 301E66 ACRIS roster · RPT-008 unit owners · RPT-009 pipeline ×5. Breadcrumbs BC-PIPE-001..010 (Groff/Kahn, 9 E71, Barak 11J, Kellen 14G, Vasquez, sponsor ACRIS gap, Black Book apts, Barrett 12B, Indyke 10B, JFK driver). Rock-solid: RS-012 DOJ 2025 letter · RS-013 multi-party · RS-014 ACRIS owners/corp. Pattern PT-009: vertical stack in one building. Maps MAP-006/007. Next: FU-020 ACRIS deed PDFs · FU-019 IA EpsteinDocs selective · FU-012 unit list.",
    waypoints: [
      {
        id: "e66-0",
        name: "Dalton School / pre-Wexner origin",
        city: "New York",
        country: "United States",
        lat: 40.785,
        lng: -73.956,
        stage: "lead",
        date: "1974-09-01",
        notes:
          "DM-2 Dalton kompromat origin: 1974–1976 math/physics teaching hire (no college degree) under Donald Barr as 'unconventional.' Susan F. Semel historian interviews (2019) on flashy behavior / rich-parent access. Vault treats Dalton as the early leverage-hook node before Bear Stearns and Wexner cash. Brooklyn birth 1953 sits in the same NYC orbit (timeline PDF).",
        exhibits: ["DM-2 Dalton", "Semel 2019 interviews", "Timeline PDF origin"],
      },
      {
        id: "e66-1",
        name: "301 East 66th Street",
        city: "New York",
        country: "United States",
        lat: 40.7651,
        lng: -73.9614,
        stage: "field",
        date: "2000-01-01",
        notes:
          "Core address for the East 66 network vault. Multi-party ownership stack (RS-013), unit-owner roster (RPT-007/008), Indyke orbit (PL-INDYKE, RPT-005). BC-PIPE unit crumbs: Barak 11J, Kellen 14G, Barrett 12B, Indyke 10B, Vasquez. Pattern PT-009: many nodes stacked in one vertical building. Sponsor ACRIS gap flagged.",
        exhibits: [
          "RS-013 multi-party",
          "RPT-007 ACRIS roster",
          "BC-PIPE units",
          "MAP-006/007",
        ],
      },
      {
        id: "e66-2",
        name: "9 East 71st Street",
        city: "New York",
        country: "United States",
        lat: 40.7712,
        lng: -73.9668,
        stage: "transit",
        date: "2001-06-01",
        notes:
          "Breadcrumb BC-PIPE for 9 E71 in the pipeline chain with Groff/Kahn and related apartment stack. Cross-file with Black Book apartment pins and sponsor ACRIS gap notes from the 1953 vault.",
        exhibits: ["BC-PIPE 9 E71", "Black Book apts", "Sponsor ACRIS gap"],
      },
      {
        id: "e66-3",
        name: "El Brillo Way mansion",
        city: "Palm Beach",
        country: "United States",
        lat: 26.7056,
        lng: -80.0364,
        stage: "evidence",
        date: "2005-03-15",
        notes:
          "Florida residence node (El Brillo Way) tying East 66 to Palm Beach police/probe years 2005–2008 NPA era. Timeline PDF: massage hub, local recruitment, 2005 raid start. Cross-walked to Reiter promotion history (DM-7). Public ceiling only — NPA DocumentCloud exhibits live in Drive Epstein specific.",
        exhibits: [
          "El Brillo Way",
          "2005 raid era",
          "NPA DocumentCloud",
          "RPT-009 pipeline",
        ],
      },
      {
        id: "e66-4",
        name: "JFK / Queens transit edge",
        city: "New York",
        country: "United States",
        lat: 40.6413,
        lng: -73.7781,
        stage: "transit",
        date: "2019-07-01",
        notes:
          "Airport edge of the NYC vault: flight-log and driver breadcrumbs (BC-PIPE JFK driver). Geographic hinge between Manhattan addresses and long-haul legs on the Lolita Express corridor.",
        exhibits: ["BC-PIPE JFK driver", "Flight-log hinge"],
      },
      {
        id: "e66-5",
        name: "Internet Archive EpsteinDocs",
        city: "San Francisco",
        country: "United States",
        lat: 37.7749,
        lng: -122.4194,
        stage: "analysis",
        date: "2025-11-01",
        notes:
          "Archive.org EpsteinDocs bucket from Drive file 'epstein all pdfs archive link.txt' → ia600705.us.archive.org/21/items/epsteindocs/ + DocumentCloud NPA mirror. RPT-004 DocumentCloud/IA; follow-up FU-019 selective IA pull. Rock-solid RS-012 DOJ 2025 letter sits here as public index. Master distill §8 next leads open from this node.",
        exhibits: ["IA EpsteinDocs URL", "RPT-004", "FU-019", "RS-012 DOJ letter"],
      },
    ],
  },
  {
    id: "eastern-feeder",
    code: "EF-02",
    title: "Eastern Feeder",
    subtitle: "Karin / Nadia / Marcinko / Lolita Express",
    status: "active",
    color: "#9aadc2",
    summary:
      "From CORE + PART1–5 + Epstein-Maxwell-timeline PDF (Mar 26 2026 swarm extract): Eastern Europe feeder mapped as recruiter → fixer → pilot → heir → shield. Zuzana Nováková (Karin recruiter, Slovakia 1996–1999, vanish 2000), Peter Marcinko (avionics aliases Marcinkov/Marchenko / Kyiv shipments / Stank–Čič MoD 'humanitarian' waivers), Nadia Marcinko / Naďa Marcinková (Košice 1986, O-1 1999 age 13, Lolita Express pilot, Aviloop CEO, missing post-Jan 2024), Jean-Luc Brunel (Karin/MC2 Paris). Dialect bleed Nadazia→Lola/Lita→Lolita as pipeline marker. Public sources in vault: flight logs, unsealed Giuffre filings, Slovak export/waiver notes, 2024–2026 press on Nadia disappearance. Recap PDFs log alias/variation hunt (Marcinkova/Marcinko/Nadežda/Global Girl).",
    waypoints: [
      {
        id: "ef-0",
        name: "Košice dialect origin",
        city: "Košice",
        country: "Slovakia",
        lat: 48.7164,
        lng: 21.2611,
        stage: "lead",
        date: "1986-01-01",
        notes:
          "Timeline PDF places Nadia birth 1986 in Košice (eastern Slovakia industrial hub, Ukraine border). Abov dialect: Naďa → Nadazia (ň glide + -zia affectionate) → Lola/Lita playground clip → Lolita nickname weaponized. Seed of the dialect-bleed method (DM-9 / PART2).",
        exhibits: ["Košice 1986", "Dialect bleed", "Timeline PDF places"],
      },
      {
        id: "ef-1",
        name: "Karin recruiter origin",
        city: "Bratislava",
        country: "Slovakia",
        lat: 48.1486,
        lng: 17.1077,
        stage: "lead",
        date: "1996-01-01",
        notes:
          "1996–1999: Zuzana Nováková as Karin Models recruiter node (PART2 / CORE). Eastern feeder starts here. Name variants + modeling-agency payroll mirrors (Wayback 2001 Paris branch 'Zuzana Novak') in recap. Vanishes 2000 — no body; vault logs Mossad-pull hypothesis as unproven.",
        exhibits: ["Zuzana / Karin 1996–99", "PART2 recruiter log", "Wayback payroll"],
      },
      {
        id: "ef-2",
        name: "Avionics / waiver corridor",
        city: "Kyiv",
        country: "Ukraine",
        lat: 50.4501,
        lng: 30.5234,
        stage: "transit",
        date: "1999-06-01",
        notes:
          "Peter Marcinko aliases (Marcinkov/Marchenko) avionics exports and Kyiv shipments 1999–2000; Stank/Čič MoD 'humanitarian' waiver covers (CORE). Duplicate Slovak passport renewals 1998/2000 noted in recap. Transit grease for the feeder chain.",
        exhibits: ["Marcinko aliases", "MoD waiver notes", "Avionics cover"],
      },
      {
        id: "ef-3",
        name: "Karin / MC2 Paris",
        city: "Paris",
        country: "France",
        lat: 48.8566,
        lng: 2.3522,
        stage: "field",
        date: "2000-01-01",
        notes:
          "Jean-Luc Brunel / Karin / MC2 scout node for Eastern pipeline (PART2). Paris is the modeling-agency hinge between Slovak/Ukrainian feeder and Western destinations. 'Paris contracts' = fake gigs → island path in timeline PDF. Brunel suicide 2022 logged on Maxwell Line cleanup.",
        exhibits: ["Brunel / Karin / MC2", "Paris scout hinge", "O-1 sponsor path"],
      },
      {
        id: "ef-4",
        name: "Lolita Express Florida base",
        city: "Palm Beach",
        country: "United States",
        lat: 26.7056,
        lng: -80.0364,
        stage: "evidence",
        date: "2002-01-01",
        notes:
          "Nadia as pilot node on Lolita Express / Boeing 727 (CORE/PART2/timeline): O-1 visa 1999; 2002–2005 legs; 200+ legs cited in vault extract; 2008 NPA immunity as unindicted co-conspirator; FAA pilot certs / Aviloop CEO later. Dialect bleed Nadazia→Lolita as pipeline marker. 2026 unseals: 'N. Marcinko' logs.",
        exhibits: [
          "Nadia pilot",
          "O-1 1999",
          "NPA 2008 co-conspirators",
          "N. Marcinko logs",
        ],
      },
      {
        id: "ef-5",
        name: "Little St. James",
        city: "Charlotte Amalie",
        country: "U.S. Virgin Islands",
        lat: 18.3005,
        lng: -64.8252,
        stage: "analysis",
        date: "2019-07-01",
        notes:
          "Island end of the feeder/flight chain (bought 1998 per timeline). Cross-walk victims list from unsealed Giuffre v. Maxwell filings (named in PART2 as public filing set) and later 2024 Nadia-missing press. 2026 aerial photos unsealed noted in timeline PDF.",
        exhibits: [
          "USVI island node",
          "Giuffre filings set",
          "Nadia missing 2024",
          "2026 aerial unseals",
        ],
      },
    ],
  },
  {
    id: "maxwell-line",
    code: "MX-03",
    title: "Maxwell Line",
    subtitle: "Inheritance / shield / cleanup / Oversight",
    status: "active",
    color: "#a8b8a4",
    summary:
      "Robert Maxwell → 1991 Lady Ghislaine yacht death → Ghislaine inheritance (Pergamon/Mossad playbook hypothesis in CORE) → Epstein/Wexner cash arm 1991 PoA → Acosta 2008 NPA shield → 2019–2022 deaths/convictions → 2026 Oversight cycle. CORE timeline + master distill systems table + timeline PDF persons. Public anchors: yacht death 1991, Wexner PoA 1991, 2008 NPA, Ghislaine conviction 2021/2022 sentence, House Oversight Feb 26 2026 'I'm done' walk-off coverage, DOJ page-dump / redaction cycle (B.C., H.C., E.B., A.D., L.W., P.A. initials in PART2). Brunel suicide 2022 and Middleton 2022 Arkansas node logged as public cleanup-adjacent events — physics claims remain hypothesis-class.",
    waypoints: [
      {
        id: "mx-1",
        name: "Maxwell London / Pergamon",
        city: "London",
        country: "United Kingdom",
        lat: 51.5074,
        lng: -0.1278,
        stage: "lead",
        date: "1985-01-01",
        notes:
          "1980s Robert Maxwell media/arms-front node in CORE timeline; Pergamon Press 1951 (Maxwell/Rosbaud) as cash/publishing seed. Ghislaine groomed in this orbit. Seed of the inheritance chain before the yacht death.",
        exhibits: ["Robert Maxwell 1980s", "Pergamon Press", "CORE timeline seed"],
      },
      {
        id: "mx-2",
        name: "Lady Ghislaine death waters",
        city: "Las Palmas",
        country: "Spain",
        lat: 28.1235,
        lng: -15.4363,
        stage: "transit",
        date: "1991-11-05",
        notes:
          "1991 yacht death near Canary Islands waters (CORE/PART3/timeline). Vault narrative treats this as the inheritance hinge: Ghislaine takes the playbook; Epstein hooks via Wexner cash/PoA the same year. No full autopsy notes in public stack.",
        exhibits: ["1991 yacht death", "Inheritance hinge", "Wexner PoA 1991"],
      },
      {
        id: "mx-3",
        name: "Wexner / NYC cash arm",
        city: "New York",
        country: "United States",
        lat: 40.758,
        lng: -73.9855,
        stage: "field",
        date: "1991-12-01",
        notes:
          "Les Wexner power of attorney 1991, townhouse-for-$1 pattern (DM-1). Columbus L Brands HQ is the corporate cash source; NYC is the control node. DISCOVERY_METHOD_1: zero-background control of billions as kompromat/leverage hypothesis origin. Pisar bridge noted in timeline PDF.",
        exhibits: ["Wexner PoA 1991", "Townhouse $1 pattern", "DM-1 Wexner/Maxwell"],
      },
      {
        id: "mx-3b",
        name: "Acosta SDFL plea shield",
        city: "Miami",
        country: "United States",
        lat: 25.7617,
        lng: -80.1918,
        stage: "evidence",
        date: "2008-06-30",
        notes:
          "Alexander Acosta as U.S. Attorney SDFL: 2008 NPA — 13 months + work release; 'intelligence asset' comment in public lore; immunity blanket for named co-conspirators (Nadia, Ghislaine, Brunel per CORE). 2019 Labor Secretary resignation under Epstein backlash. Drive holds DocumentCloud NPA PDFs.",
        exhibits: ["NPA 2008", "Acosta shield", "DocumentCloud NPA"],
      },
      {
        id: "mx-4",
        name: "MCC / 2019 death node",
        city: "New York",
        country: "United States",
        lat: 40.7135,
        lng: -74.0015,
        stage: "evidence",
        date: "2019-08-10",
        notes:
          "MCC Manhattan death node (public OCME suicide ruling; OIG jail-failure findings; SDNY nolle). Master distill §3B separates 'did he die in that cell' questions from identity-conspiracy tracks. 2026 unseals cycle continues to feed this node.",
        exhibits: ["MCC 2019", "OCME ruling", "OIG jail failure", "Public ceiling"],
      },
      {
        id: "mx-4b",
        name: "Middleton Arkansas node",
        city: "Little Rock",
        country: "United States",
        lat: 34.7465,
        lng: -92.2896,
        stage: "evidence",
        date: "2022-05-07",
        notes:
          "Mark Middleton 2022 death (shotgun/rope/cliff physics discussion in CORE/PART2; Arkansas coroner notes; Clinton White House ties in public reporting). Vault logs staged-death hypothesis as high-risk / not RS-tagged. Photos sealed in public narrative.",
        exhibits: ["Middleton 2022", "Arkansas coroner notes", "Hypothesis — not RS"],
      },
      {
        id: "mx-5",
        name: "FCI Tallahassee (Maxwell)",
        city: "Tallahassee",
        country: "United States",
        lat: 30.4383,
        lng: -84.2807,
        stage: "evidence",
        date: "2022-06-28",
        notes:
          "Ghislaine conviction (2021) / 20-year sentence (2022) custody node. Vault notes include 2026 Bryan deposition video jaw/eyes mismatch speculation (NDTV/CNN/India Today) — logged as media claim, not closed proof.",
        exhibits: ["Conviction/custody 2022", "2026 deposition video claims"],
      },
      {
        id: "mx-6",
        name: "House Oversight cycle",
        city: "Washington",
        country: "United States",
        lat: 38.8899,
        lng: -77.0091,
        stage: "analysis",
        date: "2026-02-26",
        notes:
          "Feb 26 2026 Oversight deposition storm-out coverage in CORE ('I'm done' / table-slam narrative). DOJ page-dump / redaction cycle (~3.5M pages cited) with initials B.C., H.C., E.B. (Barak), A.D. (Dershowitz), L.W. (Wexner), P.A. (Andrew) in PART2. Public political layer of the Maxwell line. Drive holds Robert Maxwell Epstein BARAK CONNECTIONS PDFs.",
        exhibits: [
          "Oversight Feb 2026",
          "DOJ dump/redactions",
          "Barak connections PDF",
          "PART3 2026 block",
        ],
      },
    ],
  },
  {
    id: "palm-beach-pete",
    code: "PBP-04",
    title: "Palm Beach Pete",
    subtitle: "Identity hypothesis (contradicted)",
    status: "paused",
    color: "#c9bba6",
    summary:
      "Master distill §3B + DISCOVERY_METHODS 3–8 + procedures: viral Mar 19 2026 I-95 'Palm Beach Pete' clip → Peter Bart Simel public identity (b. 1955-02-14 NYC, Syracuse 1977, commercial RE, RHONY S4 2011) → 1996 Middlebury magazine comma nickname ('Corky Elwell's son, Peter… West Palm Beach, Pete') → real Peter Elwell / Reiter Palm Beach police chain → Wheatley alumni Engoron orbit → Dubai container pivot theory (DM-8). MASTER DISTILL VERDICT: resemblance + geography + files-cycle timing explain why people ask; different birth year vs Epstein 1953-01-20, Bravo tape, LLC/campaign trail, facial mismatch notes, denials = identity FAILS on public record. Separate 'cell death' questions from 'is this tennis guy him.' Status paused as contradicted identity track. Drive: Palm Beach Pete/, Middlebury/ magazine PDFs, Hypothesis Simel PDFs.",
    waypoints: [
      {
        id: "pbp-0",
        name: "Wheatley alumni / Engoron orbit",
        city: "Old Westbury",
        country: "United States",
        lat: 40.7887,
        lng: -73.599,
        stage: "lead",
        date: "2023-10-17",
        notes:
          "DM-6: Wheatley High alumni newsletter #122 (Oct 17 2023) photo L-R Gary Simel, Art Engoron, Peter Simel. Engoron as alumni editor / Florida golf outings. Logged as protection-network red flag in operator procedures — pattern matching only, not proof of identity or conspiracy.",
        exhibits: ["Wheatley #122", "DM-6 Engoron", "Alumni photo caption"],
      },
      {
        id: "pbp-1",
        name: "1996 Middlebury magazine ad",
        city: "Middlebury",
        country: "United States",
        lat: 44.0153,
        lng: -73.1676,
        stage: "lead",
        date: "1996-01-01",
        notes:
          "Middlebury College Magazine Vol. 70 No. 4 archive (Drive Middlebury folder + IA djvu): 'Corky Elwell's son, Peter… West Palm Beach, Pete.' DISCOVERY_METHOD_4: comma phrasing as nickname hinge. Same year Epstein Palm Beach house purchase noted as alias-setup coincidence in vault — not identity proof.",
        exhibits: ["Middlebury Vol.70 No.4", "Comma nickname", "DM-4", "IA magazine PDF"],
      },
      {
        id: "pbp-2",
        name: "West Palm Beach Pete orbit",
        city: "West Palm Beach",
        country: "United States",
        lat: 26.7153,
        lng: -80.0534,
        stage: "transit",
        date: "2001-03-01",
        notes:
          "Real Peter Elwell career node: assistant town manager; promotion of Michael Reiter to Palm Beach Police Chief (Mar 2001) per DM-7. Later Reiter led 2005–2008 Epstein probe while 2008 NPA still closed — local-machine pattern in the vault, not identity proof. Wikipedia Reiter PDF in Hypothesis folder.",
        exhibits: ["Elwell/Reiter 2001", "DM-7 promotion chain", "NPA local layer"],
      },
      {
        id: "pbp-3",
        name: "Syracuse / tuition cross-file",
        city: "Syracuse",
        country: "United States",
        lat: 43.0481,
        lng: -76.1474,
        stage: "field",
        date: "2009-01-01",
        notes:
          "theories.txt + Janet Epstein crossover PDF: Syracuse appears in 2026 DOJ filings (pilot's daughter tuition ~$106k 2009–2012 for Taylor Visoski). Separate Janet Epstein Advocacy Center history at SU — master distill treats name collisions carefully. Simel Syracuse 1977 alumni claim in §3B identity pack. No known professional link Janet↔Jeffrey.",
        exhibits: [
          "SU tuition filings",
          "Janet Epstein advocacy (distinct)",
          "Simel 1977 claim",
          "theories.txt",
        ],
      },
      {
        id: "pbp-4",
        name: "I-95 viral taunt clip",
        city: "Miami",
        country: "United States",
        lat: 25.7617,
        lng: -80.1918,
        stage: "evidence",
        date: "2026-03-19",
        notes:
          "Mar 19 2026 viral I-95 clip: silver-haired man as 'Palm Beach Pete' (DM-3). Zero-trace pre-2019 search vs expected millionaire footprint. Master distill: why people ask ≠ identity solid. Ritual-timing note vs Maria Kovalchuk Mar 19 2025 Dubai incident is hypothesis only. NLLA debate audio for this track lives in investigations-audio.",
        exhibits: [
          "I-95 clip Mar 2026",
          "DM-3 zero-trace",
          "Identity fails tag",
          "NLLA pete audio",
        ],
      },
      {
        id: "pbp-5",
        name: "Dubai container pivot theory",
        city: "Dubai",
        country: "United Arab Emirates",
        lat: 25.2048,
        lng: 55.2708,
        stage: "analysis",
        date: "2026-02-13",
        notes:
          "DM-8: post-2019 disappearance → Dubai/DP World bin Sulayem protection window 2019–2026; Feb 13 2026 resignation sync with unseals; jet→container logistics hypothesis via Kintetsu; O-1 mirror pattern. Logged as operator theory, not rock-solid RS tag. Master distill forbids promoting Simel=Epstein as solid.",
        exhibits: ["DM-8 Dubai pivot", "DP World window", "Theory — not RS"],
      },
    ],
  },
  {
    id: "dalton-wexner",
    code: "DW-05",
    title: "Dalton–Wexner Ladder",
    subtitle: "Kompromat origin → cash control",
    status: "active",
    color: "#b8a89a",
    summary:
      "DISCOVERY_METHOD_1 + DM-2 + INVESTIGATION_PROCEDURES synthesis: chronological public-record ladder from Dalton School access (1974–1976) → Bear Stearns (1976) → Wexner meeting 1986 → full power of attorney 1991 (signing checks, moving hundreds of millions, NYC townhouse for $1) cross-timed with Robert Maxwell yacht death 1991 and Ghislaine inheritance of Pergamon playbook. Method: pure pattern recognition from unsealed files — 'zero-background nobody suddenly controls billions.' Columbus L Brands HQ as cash source; NYC as control; Palm Beach as operational residence. Feeds East 66 and Maxwell Line.",
    waypoints: [
      {
        id: "dw-1",
        name: "Dalton School access",
        city: "New York",
        country: "United States",
        lat: 40.785,
        lng: -73.956,
        stage: "lead",
        date: "1974-09-01",
        notes:
          "DM-2: Dalton hire under Donald Barr; no degree; Susan F. Semel historian interviews describe flashy behavior and elite-parent orbit. Vault hypothesis: school access as early kompromat collection surface. Not equated to later crimes without evidence.",
        exhibits: ["DM-2 Dalton", "Barr hire", "Semel interviews"],
      },
      {
        id: "dw-2",
        name: "Bear Stearns entry",
        city: "New York",
        country: "United States",
        lat: 40.758,
        lng: -73.9855,
        stage: "transit",
        date: "1976-06-01",
        notes:
          "Timeline PDF: Bear Stearns 1976 via parent/network hookup after Dalton. Bridge year between school access and later financier persona. Public career node only.",
        exhibits: ["Bear Stearns 1976", "Timeline PDF career"],
      },
      {
        id: "dw-3",
        name: "Wexner / L Brands cash source",
        city: "Columbus",
        country: "United States",
        lat: 39.9612,
        lng: -82.9988,
        stage: "field",
        date: "1986-01-01",
        notes:
          "DM-1: 1986 Wexner meeting (Victoria's Secret / L Brands billionaire orbit). Columbus as corporate HQ cash source. Later full PoA 1991 moves hundreds of millions — zero-resume control pattern that started the operator's 2020 file grind.",
        exhibits: ["Wexner 1986 meeting", "L Brands HQ", "DM-1 pattern"],
      },
      {
        id: "dw-4",
        name: "NYC townhouse / PoA control",
        city: "New York",
        country: "United States",
        lat: 40.7651,
        lng: -73.9614,
        stage: "evidence",
        date: "1991-12-01",
        notes:
          "1991 full power of attorney + townhouse-for-$1 pattern (DM-1). Same year as Lady Ghislaine yacht death. East 66 vertical stack (PT-009) later densifies the same Manhattan control geography. Links to E66-01 vault.",
        exhibits: ["PoA 1991", "Townhouse $1", "PT-009 stack link"],
      },
      {
        id: "dw-5",
        name: "Palm Beach operational residence",
        city: "Palm Beach",
        country: "United States",
        lat: 26.7056,
        lng: -80.0364,
        stage: "analysis",
        date: "1996-01-01",
        notes:
          "House purchase ~1996 (same year as Middlebury 'Pete' ad coincidence in DM-4). Operational residence that becomes 2005 raid origin. Completes the Dalton→cash→residence ladder on the public map.",
        exhibits: ["1996 Palm Beach house", "DM-4 coincidence note", "2005 raid path"],
      },
    ],
  },
  {
    id: "archive-unseals",
    code: "AU-06",
    title: "Archive & Unseals Desk",
    subtitle: "IA / DocumentCloud / DOJ dumps",
    status: "active",
    color: "#9a9eaa",
    summary:
      "Public dump index from Drive: 'epstein all pdfs archive link.txt' → Archive.org EpsteinDocs; DocumentCloud NPA PDFs (duplicate copies in Epstein specific); Jeffrey Epstein Part 22 of 22 + full documents PDFs; All Documents - Epstein Archive; hidden epstein files search scrapes; 2026 DOJ ~3.5M page redaction cycle; Black Book unredacted torrent stub (hash only — no content ingested). Next leads per master distill §8: FU-020 ACRIS deed PDFs, FU-019 IA selective pull, Pete Sunbiz/Syracuse public pages. Ceiling: index and OCR public material only.",
    waypoints: [
      {
        id: "au-1",
        name: "DocumentCloud NPA mirror",
        city: "Washington",
        country: "United States",
        lat: 38.9072,
        lng: -77.0369,
        stage: "lead",
        date: "2008-06-30",
        notes:
          "Drive holds multiple 'Jeffrey Epstein non-prosecution agreement _ DocumentCloud' PDFs. Primary public exhibit for the 2008 shield. Cross-file with Acosta Miami node on Maxwell Line.",
        exhibits: ["DocumentCloud NPA", "RPT-004", "NPA exhibit"],
      },
      {
        id: "au-2",
        name: "Internet Archive EpsteinDocs",
        city: "San Francisco",
        country: "United States",
        lat: 37.7749,
        lng: -122.4194,
        stage: "field",
        date: "2019-08-01",
        notes:
          "Canonical public dump: https://ia600705.us.archive.org/21/items/epsteindocs/ from Drive link.txt. FU-019 selective pull is next-best lead. Also hosts Middlebury magazine source material used in DM-4.",
        exhibits: ["IA EpsteinDocs", "FU-019", "link.txt"],
      },
      {
        id: "au-3",
        name: "SDNY / MCC filing edge",
        city: "New York",
        country: "United States",
        lat: 40.7135,
        lng: -74.0015,
        stage: "evidence",
        date: "2019-07-06",
        notes:
          "Arrest/filing geography for 2019 SDNY case; later nolle and OIG materials. Drive holds large full-document PDFs and Part 22 of 22. Index only — no sealed material claimed.",
        exhibits: ["SDNY 2019", "Full documents PDF", "Part 22 of 22"],
      },
      {
        id: "au-4",
        name: "2026 DOJ dump cycle",
        city: "Washington",
        country: "United States",
        lat: 38.8899,
        lng: -77.0091,
        stage: "analysis",
        date: "2026-02-01",
        notes:
          "PART2/CORE: ~3.5M pages released with heavy redactions (initials B.C., H.C., E.B., A.D., L.W., P.A.). Syracuse tuition hits and flight-log 'N. Marcinko' lines surface in this cycle. Fuels Oversight Feb 26 storm and PBP viral-timing questions without validating identity claims.",
        exhibits: ["DOJ 3.5M pages", "Redaction initials", "2026 unseals"],
      },
      {
        id: "au-5",
        name: "Black Book / geneanet index",
        city: "New York",
        country: "United States",
        lat: 40.7128,
        lng: -74.006,
        stage: "analysis",
        date: "2026-03-01",
        notes:
          "Drive holds unredacted Black Book torrent stub (metadata only) and Geneanet 'Jeffrey Edward Epstein family tree by Mary CUMMINS' scrape + Reddit genealogy thread from theories.txt. Used for apartment-pin cross-file with East 66 BC-PIPE — not for doxx of private living people.",
        exhibits: ["Black Book stub", "Geneanet scrape", "BC-PIPE cross-file"],
      },
    ],
  },
  {
    id: "swarm-ops",
    code: "SW-07",
    title: "Swarm Ops Desk",
    subtitle: "Where the work lives",
    status: "active",
    color: "#c8ccd4",
    summary:
      "Master distill §1 systems map + Hypothesis procedures + recap swarm api MASTER: live-online-agent-swarm (Supervisor, MemoryVault, Pattern, Anticipation, Compliance, OSINT, TruthVerifier), MAIN_INVESTIGATION_1953 vault, truth-engine-integrity, epstein-core-web-automation stub, CodeSorcerer/ECHO legacy, Grok-Agent-Vault Drive dual-persist, Automation research-agents-494403-pete-epstein-watch (daily 08:00 America/New_York). NLLA 20-agent debate roster (ARA URSA LUNA REX CARLIN SMECKER …). HITL 120min grant expired 10:48Z on 2026-09-10. DM-10: swarm built to overcome repeated refusals on Middlebury ad / name traces. Ceiling: public search/OCR/index only; H7 non-public blocked; secret-store NEVER distilled. Epstein's shit/ folder holds swarm .py + env stubs — keys not ingested into Meridian.",
    waypoints: [
      {
        id: "sw-1",
        name: "GitHub swarm home",
        city: "San Francisco",
        country: "United States",
        lat: 37.7749,
        lng: -122.4194,
        stage: "lead",
        date: "2026-01-01",
        notes:
          "github.com/cantgetalonggta-png/live-online-agent-swarm — primary swarm. Also truth-engine-integrity and epstein-core-web-automation stubs. Phase 1 engines landed per distill. 30 swarms / Swarm copies folders mirror deploy artifacts.",
        exhibits: [
          "live-online-agent-swarm",
          "truth-engine-integrity",
          "Phase 1 engines",
          "30 swarms folder",
        ],
      },
      {
        id: "sw-2",
        name: "Grok-Agent-Vault (Drive)",
        city: "Mountain View",
        country: "United States",
        lat: 37.422,
        lng: -122.0841,
        stage: "transit",
        date: "2026-09-10",
        notes:
          "Drive dual-persist: audit-logs / claims / HITL / investigations / investigations-audio / mp3 / skill-tree. Folder tree under Grok-Agent-Vault. investigations + Investigations (capital I) both live. This Meridian seed is the cartographic projection of that vault.",
        exhibits: ["Drive vault map §6", "investigations dual folders", "HITL logs"],
      },
      {
        id: "sw-3",
        name: "NYC vault working set",
        city: "New York",
        country: "United States",
        lat: 40.7128,
        lng: -74.006,
        stage: "field",
        date: "2026-09-10",
        notes:
          "MAIN_INVESTIGATION_1953_TRUST_ENGORON_ROD long-running public-record vault: 301 E66, Indyke, ACRIS, DocumentCloud/IA. Breadcrumbs BC-PIPE-001..010 active on desk. Engoron name collision with Wheatley alumni note is pattern-only.",
        exhibits: ["1953 vault", "BC-PIPE-001..010", "Engoron/Rod public orbit"],
      },
      {
        id: "sw-4",
        name: "Automation watch (NY)",
        city: "New York",
        country: "United States",
        lat: 40.758,
        lng: -73.9855,
        stage: "evidence",
        date: "2026-09-10",
        notes:
          "Automation research-agents-494403-pete-epstein-watch — daily 08:00 America/New_York. NLLA debate/audio sink also maps here + investigations-audio Drive folder (nlla_v1..v6 Newsom, nlla_debate_palmbeachpete_r1, nlla_smecker_palmbeachpete). Speech layer: no fake laugh tokens.",
        exhibits: [
          "pete-epstein-watch",
          "08:00 ET cadence",
          "NLLA audio sink",
          "20-agent roster",
        ],
      },
      {
        id: "sw-5",
        name: "IA public dump / next leads",
        city: "San Francisco",
        country: "United States",
        lat: 37.779,
        lng: -122.419,
        stage: "analysis",
        date: "2026-09-11",
        notes:
          "Public dump index from epstein all pdfs archive link.txt → Archive.org EpsteinDocs. Next leads per §8: FU-020 ACRIS deeds, FU-019 IA selective, Pete Sunbiz/Syracuse public pages, Newsom EO N-79-20 if that track reopens. HITL re-ask required for H1 bulk / H3 big Drive / H8 publish / H10 PACER paid.",
        exhibits: ["IA EpsteinDocs URL", "§8 next leads", "Public ceiling", "HITL matrix"],
      },
    ],
  },
  {
    id: "public-orbit",
    code: "PO-08",
    title: "Public Orbit Nodes",
    subtitle: "Nuara / VS / open crossovers",
    status: "active",
    color: "#a4b0bc",
    summary:
      "From Investigations/4 fuckers/ and Epstein specific open scrapes: public-name crossovers that appear in the vault without being promoted to closed identity claims. Salvatore Nuara (Victoria's Secret executive orbit / public Epstein association articles in Drive Google Search PDFs). Caputo clan Argentina politics-power scrape (batimes amp). Zurab Mikeladze Chelyabinsk ballet soloist scrape (operator interest node — not Epstein-linked as fact). Leonid Leonov literary research bleed (DETAILS txt is literary analysis, not case evidence — parked as noise). Framing: orbit bookmarks for open-source follow-up only. No secret-store, no private contact (H11 blocked).",
    waypoints: [
      {
        id: "po-1",
        name: "Victoria's Secret / Nuara orbit",
        city: "New York",
        country: "United States",
        lat: 40.7549,
        lng: -73.984,
        stage: "lead",
        date: "2019-01-01",
        notes:
          "Drive '4 fuckers' holds yenibakishaber + Google Search PDFs on Salvatore Nuara / Victoria's Secret / Epstein association coverage. Wexner–VS corporate orbit already on Dalton–Wexner ladder. Bookmark for public press cross-file only.",
        exhibits: ["Nuara search PDFs", "VS corporate orbit", "4 fuckers folder"],
      },
      {
        id: "po-2",
        name: "Columbus L Brands HQ",
        city: "Columbus",
        country: "United States",
        lat: 39.9612,
        lng: -82.9988,
        stage: "transit",
        date: "1986-01-01",
        notes:
          "L Brands / Victoria's Secret HQ geography shared with Wexner cash source on DW-05. Cross-link only — Nuara orbit articles sit here as corporate context, not personal guilt assignment.",
        exhibits: ["L Brands HQ", "Wexner cash link", "Public press only"],
      },
      {
        id: "po-3",
        name: "Buenos Aires Caputo scrape",
        city: "Buenos Aires",
        country: "Argentina",
        lat: -34.6037,
        lng: -58.3816,
        stage: "field",
        date: "2024-01-01",
        notes:
          "Drive link to batimes 'Caputo clan' politics-and-power article. Operator-collected open scrape in 4 fuckers set. Not elevated to Epstein pipeline without public documentary bridge.",
        exhibits: ["Caputo clan article", "Open scrape", "Not RS"],
      },
      {
        id: "po-4",
        name: "Chelyabinsk ballet node",
        city: "Chelyabinsk",
        country: "Russia",
        lat: 55.1644,
        lng: 61.4368,
        stage: "evidence",
        date: "2020-01-01",
        notes:
          "Zurab Mikeladze soloist page at Chelyabinsk State Academic Opera and Ballet Theater saved in 4 fuckers. Operator interest / name hunt node. No verified Epstein documentary link in vault — kept as bookmark.",
        exhibits: ["Mikeladze ballet page", "Bookmark only"],
      },
      {
        id: "po-5",
        name: "Moscow literary noise filter",
        city: "Moscow",
        country: "Russia",
        lat: 55.7558,
        lng: 37.6173,
        stage: "analysis",
        date: "2026-03-01",
        notes:
          "DETAILS ¿¿¿¿ txt in 4 fuckers is extensive Leonid Leonov literary moral-compass analysis — not case evidence. Logged here as 'noise filter' so future vault crawls do not re-promote literary text into the feeder chain. Master distill §7: do not ingest unrelated wrappers as evidence.",
        exhibits: ["Leonov literary txt", "Noise filter", "§7 not evidence"],
      },
    ],
  },
];
